### ISSUE TITLE
Elasticdump doesn't work with ES 6.x

### ISSUE THREAD

**Issue by prog8** [taskrabbit/elasticsearch-dump#344]
Elasticsearch 6.x requires ```{"scroll_id" : self.lastScrollId}``` as scroll request body. Elasticdump sends only scroll id in request body instead of JSON.

This works fine in `scrollResultSet`. See body in the code below:
```
    var scrollRequest = {
      'uri': self.base.host + '/_search' + '/scroll?scroll=' + self.parent.options.scrollTime,
      'method': 'GET',
      'body':  JSON.stringify({"scroll_id" : self.lastScrollId})
    }
```

**Comment by ferronrsmith** [comment]
Changes have been incorporated into https://github.com/taskrabbit/elasticsearch-dump/pull/364

**Comment by Mannoj87** [comment]
But where should we make changes in elasticdump file.  Should I just add above snippet at the last line in file /usr/bin/elasticdump ?

**Comment by ferronrsmith** [comment]
This was already fixed in the latest release. Simply update

**Comment by Mannoj87** [comment]
# elasticdump --version
4.1.1
I'm using latest and am still facing this issue.

   { type: 'mapper_parsing_exception',
     reason: 'failed to parse',
     caused_by:
      { type: 'not_x_content_exception',
        reason: 'not_x_content_exception: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes' } } }
Thu, 29 Nov 2018 12:13:01 GMT | sent 124 objects to destination elasticsearch, wrote 0
Thu, 29 Nov 2018 12:13:01 GMT | got 127 objects from source file (offset: 1977)

**Comment by ferronrsmith** [comment]
This is a different issue. Open a new issue for this and add more information. 

1. What command were you running
1. System type (linux/windows)
1. Sample data

**Comment by Mannoj87** [comment]
Command:
elasticdump --input=/data/table-27-11-2018.json   --output=http://stg-entaero001.com:9200 --type=data --headers='{"Content-Type": "application/json"}

Linux : Ubuntu, Xenial

Sample Data:
{"_index":"table-27-11-2018","_type":"document","_id":"\u001cp:-63c9-4581-b82e-2e4ea22f45b1:__RAION_2__","_score":1,"_timestamp":15
43257001238,"fields":{"__FOADATA__.rawStorageId":["\u001cp:-63c9-4581-b82e-2e4ea22f45b1:__RAION_2__"],"time.date":["1543257001238"],"____FOADATA__.id":["501468-4ea22-f45b1"]}}

**Comment by prog8** [comment]
I think the idea was that you create another issue and not continue the discussion here. In general, your input data is incorrect at a first glance. There is no `_source` field. When you replace `fields` with `_source` it should work.
How did you build the "sample data" line?
